// <auto-generated/>
global using global::System;
global using global::System.Collections.Generic;
global using global::System.Drawing;
global using global::System.IO;
global using global::System.Linq;
global using global::System.Net.Http;
global using global::System.Threading;
global using global::System.Threading.Tasks;
global using global::System.Windows.Forms;
//global using global::System.Data.SqlClient;
using System.Data;
using System.Data.SqlClient;
namespace P1_loginpage
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
        }
        SqlConnection conn = new SqlConnection(@"Data Source=DESKTOP-MTDTGL0\MSSQLSERVER1;Initial Catalog=p1db;Integrated Security=True");
        private void button1_Click(object sender, EventArgs e)
        {
            string username,password;
            username = textBox1.Text;
            password = textBox2.Text;
            try {
                String q="SELECT * FROM login WHERE username='"+username+"' AND password='"+password+"'";
                SqlDataAdapter sda = new SqlDataAdapter(q, conn);
                DataTable dt = new DataTable();
                sda.Fill(dt);
                if (dt.Rows.Count > 0)
                {
                    username = textBox1.Text;
                    password = textBox2.Text;
                    Index form2 = new Index();
                    form2.Show();
                    this.Hide();
                }
                else
                {
                    MessageBox.Show("Invalid login -> Error");
                }
            }
            catch { MessageBox.Show("Error"); }
            finally { conn.Close();}
        }

        
    }
}